In [1]:
l = [1,2,3]

In [2]:
type(l)

list

In [2]:
import numpy as np

In [6]:
%%timeit
def add(a,b):
    return a+b

add(10,90)

330 ns ± 4.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
arr = np.array(range(50))

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(50,)

In [7]:
arr.size

50

In [8]:
arr.ndim

1

In [9]:
arr2 = np.arange(0,100,2)

In [10]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
arr.ndim

1

In [12]:
arr2.size

50

In [13]:
arr+ arr2

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [14]:
arr - arr2

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23, -24, -25,
       -26, -27, -28, -29, -30, -31, -32, -33, -34, -35, -36, -37, -38,
       -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49])

In [15]:
arr2 - arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
arr*arr2

array([   0,    2,    8,   18,   32,   50,   72,   98,  128,  162,  200,
        242,  288,  338,  392,  450,  512,  578,  648,  722,  800,  882,
        968, 1058, 1152, 1250, 1352, 1458, 1568, 1682, 1800, 1922, 2048,
       2178, 2312, 2450, 2592, 2738, 2888, 3042, 3200, 3362, 3528, 3698,
       3872, 4050, 4232, 4418, 4608, 4802])

In [17]:
arr@arr2

80850

In [18]:
sum(arr)

1225

In [19]:
arr.min()

0

In [20]:
arr.max()

49

In [21]:
arr.max()

49

In [22]:
arr.std()

14.430869689661812

In [23]:
arr.mean()

24.5

In [26]:
np.median(arr)

24.5

In [31]:
np.mod(arr,90)  #modulas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int32)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
from statistics import mode

In [33]:
mode(arr)

StatisticsError: no unique mode; found 50 equally common values

In [36]:
arr[49] = 35

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 35])

In [38]:
mode(arr)

35

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 35])

In [40]:
arr[10]

10

In [43]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 35])

In [45]:
arr[1:-10:-1]

array([], dtype=int32)

In [46]:
arr[-10:0:1]

array([], dtype=int32)

In [47]:
arr[-1:-100:-1]

array([35, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [65]:
l = [
    [1,2,4],
    [4,10,10],
]

In [66]:
type(l)

list

In [67]:
arr2d = np.array(l)

In [51]:
type(arr2d)

numpy.ndarray

In [71]:
arr2d.ndim

2

In [70]:
arr2d  

array([[ 1,  2,  4],
       [ 4, 10, 10]])

In [68]:
arr2d.mean()

5.166666666666667

In [69]:
np.median(arr2d)

4.0

In [60]:
arr2d.shape

(2, 3)

In [61]:
arr2d.size

6

In [72]:
arr2d

array([[ 1,  2,  4],
       [ 4, 10, 10]])

In [73]:
arr2d = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])

In [74]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
arr2d.shape

(4, 5)

In [77]:
arr2d[0]

array([1, 2, 3, 4, 5])

In [78]:
arr2d[3]

array([16, 17, 18, 19, 20])

In [79]:
arr2d[1,2]

8

In [80]:
arr2d[2,3]

14

In [86]:
arr2d[2:,3]

array([14, 19])

In [87]:
arr2d[:,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [88]:
arr2d[1:,2]

array([ 8, 13, 18])

In [89]:
arr3d = np.array(
[
    [
        [2,3,4],
        [5,6,7],
    ],
    [
        [10,11,12],
        [13,14,15]
    ],
    [
        [11,12,13],
        [13,14,15]
    ]
])

In [90]:
arr3d.ndim

3

In [91]:
arr3d.shape

(3, 2, 3)

In [92]:
arr3d[1]

array([[10, 11, 12],
       [13, 14, 15]])

In [93]:
arr3d[:,1,2]

array([ 7, 15, 15])

In [94]:
arr3d[:,:,1:3]

array([[[ 3,  4],
        [ 6,  7]],

       [[11, 12],
        [14, 15]],

       [[12, 13],
        [14, 15]]])

In [96]:
arr3d[1,0,1] = 50

In [97]:
arr3d

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[10, 50, 12],
        [13, 14, 15]],

       [[11, 12, 13],
        [13, 14, 15]]])

In [102]:
arr = np.linspace(-1,1,10)  #linearlyspaced elements

In [103]:
arr

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [104]:
arr.ndim

1

In [107]:
a2 = arr.reshape(5,2)

In [106]:
arr

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [108]:
a2

array([[-1.        , -0.77777778],
       [-0.55555556, -0.33333333],
       [-0.11111111,  0.11111111],
       [ 0.33333333,  0.55555556],
       [ 0.77777778,  1.        ]])

In [ ]:
a1 = np.random.random(0,10,27)